/*
SQLyog v10.2 
MySQL - 5.6.40-log : Database - fit
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
USE `fit`;

/*Table structure for table `lms_exam_log` */

CREATE TABLE `lms_exam_log` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `USER_ID` bigint(30) NOT NULL COMMENT '用户ID',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '用户名',
  `EXAM_ROOM_ID` bigint(30) NOT NULL COMMENT '答题室ID',
  `EXAM_ROOM_NAME` varchar(50) DEFAULT NULL COMMENT '答题室名',
  `SCORE` int(4) DEFAULT '0' COMMENT '得分',
  `TIME_ON` datetime DEFAULT NULL COMMENT '开始时间',
  `TIME_OFF` datetime DEFAULT NULL COMMENT '结束时间',
  `TOTAL_QUESTIONS` int(11) DEFAULT '0' COMMENT '总题数',
  `CORRECT_QUESTIONS` int(11) DEFAULT '0' COMMENT '正确题数',
  `WRONG_QUESTIONS` int(11) DEFAULT '0' COMMENT '错误题数',
  PRIMARY KEY (`ID`),
  KEY `idx_user` (`USER_ID`),
  KEY `idx_exam_room` (`EXAM_ROOM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='答题统计表';

/*Data for the table `lms_exam_log` */

insert  into `lms_exam_log`(`ID`,`CTIME`,`USER_ID`,`USER_NAME`,`EXAM_ROOM_ID`,`EXAM_ROOM_NAME`,`SCORE`,`TIME_ON`,`TIME_OFF`,`TOTAL_QUESTIONS`,`CORRECT_QUESTIONS`,`WRONG_QUESTIONS`) values (1,'2017-11-11 00:00:00',1,'admin',2,'答题室1',100,NULL,NULL,1,1,0);

/*Table structure for table `lms_exam_room` */

CREATE TABLE `lms_exam_room` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '答题室ID',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `UUID` varchar(36) NOT NULL,
  `SUBJECT_ID` bigint(30) NOT NULL COMMENT '所属学科ID',
  `SUBJECT_NAME` varchar(100) DEFAULT NULL COMMENT '所属学科名',
  `IMG_ID` bigint(30) DEFAULT NULL COMMENT '考场图标ID',
  `NAME` varchar(100) NOT NULL COMMENT '答题室名称',
  `CONTENT` text COMMENT '答题室说明',
  `LEVEL` varchar(20) DEFAULT NULL COMMENT '难度等级',
  `NOTES` varchar(255) DEFAULT NULL COMMENT '答题室描述',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '1' COMMENT '答题室状态: 0-停用,1-新建,2-发布,3-结束,4-归档''',
  `SHARE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否公开 0-公开 1-私有',
  `EXAM_MODE` int(1) NOT NULL DEFAULT '0' COMMENT '答卷模式: 0-标准答题模式,1-随机抽取模式,2-习题练习模式,3-只读学习模式',
  `TIME_MODE` tinyint(1) DEFAULT '0' COMMENT '时间类型: 0-永久,1-限时',
  `TIME_LEN` int(4) DEFAULT NULL COMMENT '答题时长(分钟)',
  `TIME_ON` datetime DEFAULT NULL COMMENT '开始时间',
  `TIME_OFF` datetime DEFAULT NULL COMMENT '结束时间',
  `EXAMINEE_MODE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '答题人员模式: 0-任何人员,1-指定人员',
  `EXAMINEE_COUNT` int(4) NOT NULL DEFAULT '0' COMMENT '答题次数',
  `SUBJECT_SORT_MODE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '答卷展示题目排序: 0-固定,1-随机',
  `SUBJECT_OPT_SORT_MODE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '答卷展示选项排序: 0-固定,1-随机',
  `ADJUDGE_MODE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '判卷类型: 0-用户交卷后,1-全场收卷后',
  `MARK_MODE` tinyint(1) NOT NULL DEFAULT '0' COMMENT '阅卷类型: 0-自动&人工,1-人工',
  `MARK_SHOW_MODE` int(1) DEFAULT NULL COMMENT '成绩类型: 0-得分&答卷,1-得分,2-答卷',
  `MARK_TIME_MODE` int(1) DEFAULT NULL COMMENT '成绩时间类型: 0-不发布,1-全场阅卷后,2-答卷阅卷后',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`),
  KEY `idx_subject` (`SUBJECT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='答题室表';

/*Data for the table `lms_exam_room` */

insert  into `lms_exam_room`(`ID`,`CTIME`,`CUSER`,`UUID`,`SUBJECT_ID`,`SUBJECT_NAME`,`IMG_ID`,`NAME`,`CONTENT`,`LEVEL`,`NOTES`,`ENABLED`,`SHARE`,`EXAM_MODE`,`TIME_MODE`,`TIME_LEN`,`TIME_ON`,`TIME_OFF`,`EXAMINEE_MODE`,`EXAMINEE_COUNT`,`SUBJECT_SORT_MODE`,`SUBJECT_OPT_SORT_MODE`,`ADJUDGE_MODE`,`MARK_MODE`,`MARK_SHOW_MODE`,`MARK_TIME_MODE`,`ETIME`,`EUSER`) values (1,'2020-08-27 17:03:11',1,'e1301575-d682-11f0-9a07-fcaa144eb7f0',1,'演示学类',NULL,'默认答题室','答题室内容说明',NULL,'默认答题室备注',2,0,0,0,3,NULL,NULL,0,0,0,0,0,0,NULL,NULL,NULL,NULL);
insert  into `lms_exam_room`(`ID`,`CTIME`,`CUSER`,`UUID`,`SUBJECT_ID`,`SUBJECT_NAME`,`IMG_ID`,`NAME`,`CONTENT`,`LEVEL`,`NOTES`,`ENABLED`,`SHARE`,`EXAM_MODE`,`TIME_MODE`,`TIME_LEN`,`TIME_ON`,`TIME_OFF`,`EXAMINEE_MODE`,`EXAMINEE_COUNT`,`SUBJECT_SORT_MODE`,`SUBJECT_OPT_SORT_MODE`,`ADJUDGE_MODE`,`MARK_MODE`,`MARK_SHOW_MODE`,`MARK_TIME_MODE`,`ETIME`,`EUSER`) values (2,'2020-08-27 17:03:11',1,'361eaefa-d683-11f0-9a07-fcaa144eb7f0',2,'演示科目',NULL,'答题室1','答题室1',NULL,'答题室1备注',2,0,0,0,5,NULL,NULL,0,0,0,0,0,0,NULL,NULL,NULL,NULL);
insert  into `lms_exam_room`(`ID`,`CTIME`,`CUSER`,`UUID`,`SUBJECT_ID`,`SUBJECT_NAME`,`IMG_ID`,`NAME`,`CONTENT`,`LEVEL`,`NOTES`,`ENABLED`,`SHARE`,`EXAM_MODE`,`TIME_MODE`,`TIME_LEN`,`TIME_ON`,`TIME_OFF`,`EXAMINEE_MODE`,`EXAMINEE_COUNT`,`SUBJECT_SORT_MODE`,`SUBJECT_OPT_SORT_MODE`,`ADJUDGE_MODE`,`MARK_MODE`,`MARK_SHOW_MODE`,`MARK_TIME_MODE`,`ETIME`,`EUSER`) values (3,'2020-08-27 17:03:11',1,'d2dfd589-d684-11f0-9a07-fcaa144eb7f0',3,'演示数学',NULL,'演示数学','演示数学',NULL,'演示数学',2,0,0,0,10,NULL,NULL,0,0,0,0,0,0,NULL,NULL,NULL,NULL);
insert  into `lms_exam_room`(`ID`,`CTIME`,`CUSER`,`UUID`,`SUBJECT_ID`,`SUBJECT_NAME`,`IMG_ID`,`NAME`,`CONTENT`,`LEVEL`,`NOTES`,`ENABLED`,`SHARE`,`EXAM_MODE`,`TIME_MODE`,`TIME_LEN`,`TIME_ON`,`TIME_OFF`,`EXAMINEE_MODE`,`EXAMINEE_COUNT`,`SUBJECT_SORT_MODE`,`SUBJECT_OPT_SORT_MODE`,`ADJUDGE_MODE`,`MARK_MODE`,`MARK_SHOW_MODE`,`MARK_TIME_MODE`,`ETIME`,`EUSER`) values (4,'2020-08-27 17:03:11',1,'ea596647-d684-11f0-9a07-fcaa144eb7f0',4,'演示语文',NULL,'演示语文','演示语文',NULL,'演示语文',2,0,0,0,10,NULL,NULL,0,0,0,0,0,0,NULL,NULL,NULL,NULL);

/*Table structure for table `lms_exam_subject` */

CREATE TABLE `lms_exam_subject` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '学科ID',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `PID` bigint(30) NOT NULL DEFAULT '0' COMMENT '父级ID,支持多级分类',
  `NAME` varchar(30) NOT NULL COMMENT '学科名称',
  `SORT` int(5) DEFAULT '0' COMMENT '排序',
  `LEVELS` int(1) DEFAULT '0' COMMENT '学科层级,0为顶级',
  `NOTES` varchar(50) DEFAULT NULL COMMENT '备注',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8 COMMENT='学科分类表';

/*Data for the table `lms_exam_subject` */

insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (1,'2020-08-27 17:03:11',1,0,'演示学类',0,0,'演示学类',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (2,'2020-08-27 17:03:11',1,1,'演示科目',1,0,'演示科目',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (3,'2020-08-27 17:03:11',1,0,'数学',1,0,'数学总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (4,'2020-08-27 17:03:11',1,0,'语文',2,0,'语文总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (5,'2020-08-27 17:03:11',1,0,'英语',3,0,'英语总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (6,'2020-08-27 17:03:11',1,0,'政治',4,0,'政治总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (7,'2020-08-27 17:03:11',1,0,'历史',5,0,'历史总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (8,'2020-08-27 17:03:11',1,0,'地理',6,0,'地理总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (9,'2020-08-27 17:03:11',1,0,'物理',7,0,'物理总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (10,'2020-08-27 17:03:11',1,0,'化学',8,0,'化学总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (11,'2020-08-27 17:03:11',1,0,'生物',9,0,'生物总纲',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (12,'2020-08-27 17:03:11',1,3,'一年级',1,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (13,'2020-08-27 17:03:11',1,3,'二年级',2,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (14,'2020-08-27 17:03:11',1,3,'三年级',3,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (15,'2020-08-27 17:03:11',1,3,'四年级',4,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (16,'2020-08-27 17:03:11',1,3,'五年级',5,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (17,'2020-08-27 17:03:11',1,3,'六年级',6,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (18,'2020-08-27 17:03:11',1,3,'七年级',7,0,'初一',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (19,'2020-08-27 17:03:11',1,3,'八年级',8,0,'初二',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (20,'2020-08-27 17:03:11',1,3,'九年级',9,0,'初三',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (21,'2020-08-27 17:03:11',1,4,'一年级',1,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (22,'2020-08-27 17:03:11',1,4,'二年级',2,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (23,'2020-08-27 17:03:11',1,4,'三年级',3,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (24,'2020-08-27 17:03:11',1,4,'四年级',4,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (25,'2020-08-27 17:03:11',1,4,'五年级',5,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (26,'2020-08-27 17:03:11',1,4,'六年级',6,0,'',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (27,'2020-08-27 17:03:11',1,4,'七年级',7,0,'初一',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (28,'2020-08-27 17:03:11',1,4,'八年级',8,0,'初二',1,NULL,NULL);
insert  into `lms_exam_subject`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`SORT`,`LEVELS`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (29,'2020-08-27 17:03:11',1,4,'九年级',9,0,'初三',1,NULL,NULL);

/*Table structure for table `lms_question` */

CREATE TABLE `lms_question` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '题目ID',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `EXAM_ROOM_ID` bigint(30) DEFAULT NULL COMMENT '所属答题室ID',
  `EXAM_ROOM_NAME` varchar(50) DEFAULT NULL COMMENT '所属答题室名',
  `MOLD` int(1) NOT NULL DEFAULT '0' COMMENT '题类型：0-单选,1-多选,2-判断',
  `CONTENT` text NOT NULL COMMENT '题目内容',
  `DIFFICULTY` int(1) DEFAULT '1' COMMENT '难度等级 1-5',
  `SHARE` tinyint(1) DEFAULT '1' COMMENT '题目是否公开: 0-私有,1-公开',
  `ENABLED` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`),
  KEY `idx_exam_room` (`EXAM_ROOM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='题目表';

/*Data for the table `lms_question` */

insert  into `lms_question`(`ID`,`CTIME`,`CUSER`,`EXAM_ROOM_ID`,`EXAM_ROOM_NAME`,`MOLD`,`CONTENT`,`DIFFICULTY`,`SHARE`,`ENABLED`,`ETIME`,`EUSER`) values (1,'2020-08-27 17:03:11',1,2,'演示科目',0,'答题系统可以正常答题？',1,1,1,NULL,NULL);

/*Table structure for table `lms_question_answer` */

CREATE TABLE `lms_question_answer` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '答案ID',
  `QUESTION_ID` bigint(30) NOT NULL COMMENT '题目ID',
  `CONTENT` varchar(255) NOT NULL COMMENT '答案内容',
  `VERIFY` int(1) NOT NULL DEFAULT '0' COMMENT '答案校验: 0-无,1-正确,2-错误',
  PRIMARY KEY (`ID`),
  KEY `idx_question` (`QUESTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='题目答案表';

/*Data for the table `lms_question_answer` */

insert  into `lms_question_answer`(`ID`,`QUESTION_ID`,`CONTENT`,`VERIFY`) values (1,1,'是',0);
insert  into `lms_question_answer`(`ID`,`QUESTION_ID`,`CONTENT`,`VERIFY`) values (2,1,'否',0);

/*Table structure for table `lms_question_material` */

CREATE TABLE `lms_question_material` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `UUID` char(36) COLLATE utf8_unicode_ci DEFAULT 'uuid()',
  `TITLE` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '标题',
  `CONTENT` text COLLATE utf8_unicode_ci COMMENT '正文',
  `NOTES` text COLLATE utf8_unicode_ci COMMENT '备注',
  `ENABLED` tinyint(1) DEFAULT '0' COMMENT '禁用状态: 0-禁用,1-正常',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='题库材料';

/*Data for the table `lms_question_material` */

insert  into `lms_question_material`(`ID`,`CTIME`,`CUSER`,`UUID`,`TITLE`,`CONTENT`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (1,'2017-11-11 00:00:00',1,'1dbb53f6-ceba-11f0-8745-f8cab851439b','演示材料','<p>\r\n	白日依山尽，\r\n</p>\r\n<p>\r\n	黄河入海流。\r\n</p>\r\n<p>\r\n	欲穷千里目，\r\n</p>\r\n<p>\r\n	更上一层楼。\r\n</p>','演示材料',1,NULL,NULL);
insert  into `lms_question_material`(`ID`,`CTIME`,`CUSER`,`UUID`,`TITLE`,`CONTENT`,`NOTES`,`ENABLED`,`ETIME`,`EUSER`) values (2,'2017-11-11 00:00:00',1,'2df6c93e-cebc-11f0-8745-f8cab851439b','望庐山瀑布','<p>\r\n	日照香炉生紫烟，\r\n</p>\r\n<p>\r\n	遥看瀑布挂前川。\r\n</p>\r\n<p>\r\n	飞流直下三千尺，\r\n</p>\r\n<p>\r\n	疑是银河落九天。\r\n</p>',NULL,0,'2025-12-01 22:06:04',1);

/*Table structure for table `lms_question_wrong` */

CREATE TABLE `lms_question_wrong` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `USER_ID` bigint(30) NOT NULL COMMENT '用户ID',
  `QUESTION_ID` bigint(30) NOT NULL COMMENT '题目ID',
  `WRONG_COUNT` int(11) DEFAULT '1' COMMENT '错误次数',
  `LAST_WRONG_TIME` datetime DEFAULT NULL COMMENT '最后错误时间',
  PRIMARY KEY (`ID`),
  KEY `idx_user` (`USER_ID`),
  KEY `idx_question` (`QUESTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='错题本';

/*Data for the table `lms_question_wrong` */

insert  into `lms_question_wrong`(`ID`,`USER_ID`,`QUESTION_ID`,`WRONG_COUNT`,`LAST_WRONG_TIME`) values (1,1,1,1,'2017-11-11 00:00:00');

/*Table structure for table `lms_top` */

CREATE TABLE `lms_top` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `MODEL` int(1) NOT NULL COMMENT '模型: 0-横幅,1-课程,',
  `TITLE` varchar(128) DEFAULT NULL COMMENT '标题',
  `CONTENT` text COMMENT '内容',
  `URL` text COMMENT '访问地址',
  `IMG_ID` bigint(30) DEFAULT NULL COMMENT '图片ID',
  `MOLD` int(1) DEFAULT NULL COMMENT '类型: 1-首页推荐,2-横幅推荐',
  `VISITS` int(11) DEFAULT '0' COMMENT '访问量',
  `SORT` int(1) DEFAULT NULL COMMENT '排序',
  `ENABLED` tinyint(1) DEFAULT '0' COMMENT '禁用状态: 0-禁用,1-正常',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='首页顶部内容';

/*Data for the table `lms_top` */

insert  into `lms_top`(`ID`,`CTIME`,`CUSER`,`MODEL`,`TITLE`,`CONTENT`,`URL`,`IMG_ID`,`MOLD`,`VISITS`,`SORT`,`ENABLED`,`ETIME`,`EUSER`) values (1,'2020-08-27 17:03:11',1,1,'使用Prometheus实践基于Spring Boot监控告警体系','课程须知本课程适合有一定Java Web开发经验，熟悉Spring Boot的开发者。老师告诉你能学到什么？\r\n\r\n1、MDD的理论和微服务四层轻量监控体系 \r\n\r\n2、Prometheus架构设计 \r\n\r\n3、Prometheus+Grafana安装搭建 \r\n\r\n4、常用Metrics命令及使用技巧 \r\n\r\n5、SpringBoot 2.X集成Prometheus+Grafana \r\n\r\n6、如何配置可视化监控大盘及告警 \r\n\r\n7、Prometheus集群部署方式和一些踩坑经验',NULL,NULL,1,0,1,1,NULL,0);
insert  into `lms_top`(`ID`,`CTIME`,`CUSER`,`MODEL`,`TITLE`,`CONTENT`,`URL`,`IMG_ID`,`MOLD`,`VISITS`,`SORT`,`ENABLED`,`ETIME`,`EUSER`) values (2,'2020-08-27 17:03:11',1,0,'banner1','test',NULL,NULL,2,0,1,1,NULL,0);
insert  into `lms_top`(`ID`,`CTIME`,`CUSER`,`MODEL`,`TITLE`,`CONTENT`,`URL`,`IMG_ID`,`MOLD`,`VISITS`,`SORT`,`ENABLED`,`ETIME`,`EUSER`) values (3,'2020-08-27 17:03:11',1,0,'banner2','test2',NULL,NULL,2,0,2,1,NULL,0);

/*Table structure for table `sys_authorities` */

CREATE TABLE `sys_authorities` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `NAME` varchar(40) DEFAULT NULL COMMENT '权限名称',
  `NOTES` varchar(100) DEFAULT NULL COMMENT '权限描述',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被禁用 0禁用1正常',
  `ISYS` int(1) NOT NULL DEFAULT '0' COMMENT '是否是超级权限 0非1是',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='权限表';

/*Data for the table `sys_authorities` */

insert  into `sys_authorities`(`ID`,`CTIME`,`CUSER`,`NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (1,'2017-11-11 00:00:00',NULL,'ROOT','超级管理员',1,1,NULL,NULL);
insert  into `sys_authorities`(`ID`,`CTIME`,`CUSER`,`NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (2,'2017-11-11 00:00:00',NULL,'SYSTEM','系统管理员',1,0,NULL,NULL);
insert  into `sys_authorities`(`ID`,`CTIME`,`CUSER`,`NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (3,'2017-11-11 00:00:00',NULL,'ADMIN','管理员',1,0,NULL,NULL);
insert  into `sys_authorities`(`ID`,`CTIME`,`CUSER`,`NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (4,'2017-11-11 00:00:00',NULL,'USER','用户',1,0,NULL,NULL);

/*Table structure for table `sys_authorities_res` */

CREATE TABLE `sys_authorities_res` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `AUTH_ID` bigint(30) DEFAULT NULL COMMENT '权限id',
  `RES_ID` bigint(30) DEFAULT NULL COMMENT '资源id',
  PRIMARY KEY (`ID`),
  KEY `auth_id` (`AUTH_ID`),
  KEY `res_id` (`RES_ID`),
  CONSTRAINT `sys_authorities_res_ibfk_1` FOREIGN KEY (`AUTH_ID`) REFERENCES `sys_authorities` (`ID`),
  CONSTRAINT `sys_authorities_res_ibfk_2` FOREIGN KEY (`RES_ID`) REFERENCES `sys_resources` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='角色权限关联表';

/*Data for the table `sys_authorities_res` */

insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (1,1,1);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (2,1,2);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (3,1,3);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (4,1,4);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (5,1,5);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (6,1,6);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (7,1,7);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (8,1,8);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (9,1,9);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (10,1,10);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (11,1,11);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (12,1,12);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (13,1,13);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (14,1,14);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (15,1,15);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (16,1,16);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (17,1,17);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (18,1,18);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (19,1,19);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (20,1,20);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (21,1,21);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (22,1,22);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (23,1,23);
insert  into `sys_authorities_res`(`ID`,`AUTH_ID`,`RES_ID`) values (24,1,24);

/*Table structure for table `sys_dept` */

CREATE TABLE `sys_dept` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `PID` bigint(30) DEFAULT '0' COMMENT '父部门id',
  `PIDS` varchar(512) DEFAULT NULL COMMENT '父级ids',
  `SIMPLE_NAME` varchar(45) DEFAULT NULL COMMENT '简称',
  `FULL_NAME` varchar(255) DEFAULT NULL COMMENT '全称',
  `NOTES` varchar(255) DEFAULT NULL COMMENT '描述',
  `VERSION` int(11) DEFAULT NULL COMMENT '版本（乐观锁保留字段）',
  `SORT` int(11) DEFAULT NULL COMMENT '排序',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='部门表';

/*Data for the table `sys_dept` */

insert  into `sys_dept`(`ID`,`CTIME`,`CUSER`,`PID`,`PIDS`,`SIMPLE_NAME`,`FULL_NAME`,`NOTES`,`VERSION`,`SORT`,`ETIME`,`EUSER`) values (1,'2019-04-01 00:00:00',1,0,'-1','总公司','总公司','总公司',NULL,1,'2025-11-27 17:44:21',1);
insert  into `sys_dept`(`ID`,`CTIME`,`CUSER`,`PID`,`PIDS`,`SIMPLE_NAME`,`FULL_NAME`,`NOTES`,`VERSION`,`SORT`,`ETIME`,`EUSER`) values (2,'2019-04-01 00:00:00',1,1,'1','开发部','开发部','开发部',NULL,2,'2025-11-27 17:44:12',1);
insert  into `sys_dept`(`ID`,`CTIME`,`CUSER`,`PID`,`PIDS`,`SIMPLE_NAME`,`FULL_NAME`,`NOTES`,`VERSION`,`SORT`,`ETIME`,`EUSER`) values (3,'2019-04-01 00:00:00',1,1,'1','运营部','运营部','运营部',NULL,3,'2025-11-27 17:44:04',1);
insert  into `sys_dept`(`ID`,`CTIME`,`CUSER`,`PID`,`PIDS`,`SIMPLE_NAME`,`FULL_NAME`,`NOTES`,`VERSION`,`SORT`,`ETIME`,`EUSER`) values (4,'2019-04-01 00:00:00',1,1,'1','战略部','战略部','战略部',NULL,4,'2025-11-27 17:43:55',1);
insert  into `sys_dept`(`ID`,`CTIME`,`CUSER`,`PID`,`PIDS`,`SIMPLE_NAME`,`FULL_NAME`,`NOTES`,`VERSION`,`SORT`,`ETIME`,`EUSER`) values (5,'2019-05-05 13:03:21',1,0,NULL,'财务部','财务部','财务部',NULL,5,NULL,NULL);

/*Table structure for table `sys_dict` */

CREATE TABLE `sys_dict` (
  `ID` bigint(30) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `PID` bigint(20) DEFAULT NULL COMMENT '父级字典id',
  `NAME` varchar(255) DEFAULT NULL COMMENT '字典名称',
  `CODE` varchar(255) DEFAULT NULL COMMENT '字典的编码',
  `SIGN` varchar(1) DEFAULT NULL COMMENT '是否系统标识',
  `NOTES` varchar(255) DEFAULT NULL COMMENT '描述',
  `SORT` int(11) DEFAULT NULL COMMENT '排序',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='字典表';

/*Data for the table `sys_dict` */

insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (1,'2019-04-01 00:00:00',NULL,0,'性别','SEX',NULL,NULL,0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (2,'2019-04-01 00:00:00',NULL,1,'男','M',NULL,NULL,1,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (3,'2019-04-01 00:00:00',NULL,1,'女','F',NULL,NULL,2,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (4,'2019-04-01 00:00:00',NULL,0,'状态','STATUS',NULL,NULL,0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (5,'2019-04-01 00:00:00',NULL,4,'启用','ENABLE',NULL,NULL,1,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (6,'2019-04-01 00:00:00',NULL,4,'禁用','DISABLE',NULL,NULL,2,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (7,'2019-04-01 00:00:00',NULL,0,'账号状态','ACCOUNT_STATUS',NULL,NULL,0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (8,'2019-04-01 00:00:00',NULL,7,'启用','ENABLE',NULL,NULL,1,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (9,'2019-04-01 00:00:00',NULL,7,'冻结','FREEZE',NULL,NULL,2,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (10,'2019-04-01 00:00:00',NULL,7,'已删除','DELETED',NULL,NULL,3,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (11,'2019-04-01 00:00:00',1,0,'是否删除','DEL_FLAG',NULL,'用于数据库中是否删除的标记',0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (12,'2019-04-01 00:00:00',1,11,'已经删除','Y',NULL,NULL,1,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (13,'2019-04-01 00:00:00',1,11,'未删除','N',NULL,NULL,2,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (14,'2019-04-01 00:00:00',1,1,'保密','O','N','性别保密',3,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (15,'2019-04-01 00:00:00',1,0,'系统配置类型','SYSTEM_TYPE','Y',NULL,0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (16,'2019-04-01 00:00:00',1,15,'系统服务类型','1','N',NULL,1,'2019-05-23 18:25:48',1);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (17,'2019-04-01 00:00:00',1,15,'系统云端类型','2','N',NULL,2,'2019-05-24 10:34:32',1);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (19,'2022-06-16 17:09:54',1,0,'获奖项','AWARDS','N','',0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (20,'2022-06-16 17:15:35',1,19,'一等奖','FIRST_PRIZE','N','',1,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (21,'2022-06-16 17:15:52',1,19,'二等奖','SECOND_PRIZE','N','',2,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (22,'2022-06-16 17:16:07',1,19,'三等奖','THIRD_PRIZE','N','',3,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (23,'2022-06-16 17:16:22',1,19,'四等奖','FOURTH_PRIZE','N','',4,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (24,'2022-06-16 17:16:37',1,19,'五等奖','FIFTH_PRIZE','N','',5,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (25,'2022-06-16 17:16:55',1,19,'特等奖','SPECIAL_PRIZE','N','',6,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (26,'2022-06-17 17:27:19',1,0,'活动类型','RECORD_TYPE','N','',0,NULL,NULL);
insert  into `sys_dict`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`CODE`,`SIGN`,`NOTES`,`SORT`,`ETIME`,`EUSER`) values (27,'2022-06-17 17:28:42',1,26,'抽奖','1','N','',1,NULL,NULL);

/*Table structure for table `sys_files` */

CREATE TABLE `sys_files` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime NOT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `FILE_MOLD` int(1) DEFAULT NULL COMMENT '文件类型: 0-图片,1-文件',
  `FILE_NAME` varchar(50) DEFAULT NULL COMMENT '文件名',
  `FILE_SUFFIX` varchar(10) DEFAULT NULL COMMENT '文件后缀',
  `FILE_DATA` text COMMENT 'base64编码的文件',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被禁用 0禁用1正常',
  `ISYS` int(1) NOT NULL DEFAULT '0' COMMENT '是否是超级权限 0非1是',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='文件表';

/*Data for the table `sys_files` */

insert  into `sys_files`(`ID`,`CTIME`,`CUSER`,`FILE_MOLD`,`FILE_NAME`,`FILE_SUFFIX`,`FILE_DATA`,`ENABLED`,`ISYS`) values (1,'2025-12-04 16:45:50',1,1,'20251204file1684448727320025804.JPG',NULL,'/9j/4R/+RXhpZgAATU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAABAAAAZgAAAMAAAABIAAAAAQAAAEgAAAABAAeQAAAHAAAABDAyMjGRAQAHAAAABAECAwCgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAAAnqgAwAEAAAAAQAAAoCkBgADAAAAAQAAAAAAAAAAAAYBAwADAAAAAQAGAAABGgAFAAAAAQAAAQ4BGwAFAAAAAQAAARYBKAADAAAAAQACAAACAQAEAAAAAQAAAR4CAgAEAAAAAQAAEOEAAAAAAAAASAAAAAEAAABIAAAAAf/Y/9sAQwACAQECAQECAgECAgICAgMFAwMDAwMGBAQDBQcGBwcHBgYGBwgLCQcICggGBgkNCQoLCwwMDAcJDQ4NDA4LDAwL/9sAQwECAgIDAgMFAwMFCwgGCAsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsL/8AAEQgAoACfAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A/fyiiigAooooAKh1C9GnWcszo8giQuVRdzNgZwB3PtU1FAnqtDlB8WLaPwvHql5p+qxJLdx2iwfZXacs7KuRGBuYDJbgHgGrV78StPs/Dd/qckWoJDYKCyT2cts8zMcKkYmVdzMxCgDuwHen+PfA0fjzTktr26lit0JZoRb200c54xuFxDIOMcEAdT14rj9G+Cctr4T1a1ubLS457u7t57dEEe1THt/eN5UMaB/vj5UHAXnOabFBNRSk7s6Dw/8AGvRPEM/lQf2hC7JLKhkspgkkSc+YsgUoyspV1IPIde5xWdof7ReieIfsDabBeNDfm1RZC0K+W1xs2Ao0gkbmRclVYdecAmofCvwg1CwvbptWvjEsqvbu8MhLXUbxKHfHSJjIgZQC2xcqDzkYPhz4E614at9PtNMjsIbK3n0yeRUvCqgweQZsR+Qc5aJyP3i9Rx6oo3fHH7TGjfDzUI7XxLp2tx3DxmUqsCHYoM3JJcZyIHIIyCCPXjQ8c/HPT/APiJNM1XT9Tmmfa2+ERFFRlciRsyAquY3XJAyRiuF8R/s463rMsr2jadZlZGms1t7ry4rZmeZiGQwEnidlyjJnGeOANDx38Atf8e+Kby/l1PTbJBYQ2dsPKeZn2b2/efMuPmlcZGcjBwMcgHaXnxh02z1HSbN4rprvWrR7u1iVVO8AoFTzM+XuYyAD5sepHGYG+MDTaQbvT/D2szFLqW0eIeUzBo0LFgY3ZWXcPLyG+/kHoawm+Dmrak3httXfT8aJYC3uoQ7sl+QCioOhjCqS3mDlmKkr8grrPhX4GTwF4WFr5ENvPNNLPMkUzyopeRmADNgnCsBnAzimvMicXKLUXZ9zpKKKKRYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEF/dmziDKM89DVT+3G/uD86m1z/AI9B9ayfMq1y21MKs5RdkVD4/l/4S5NM+zptZlXzN3PIz0rra8yH/JUYj/01T/0AV6bTmkrWOfA1ZVefmd7OwUUUVmd4UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAU9c/wCPP/gVY9bGuf8AHn/wKseg5a/xHMhP+LlxH/pqn/oAr0qvItc8X2fh/wCIzNqJkAgdGbauf4Af610v/DQGg/8AT3/36/8Ar1rKLlsjzMFj8PQ9oqlRJ8z3fodxRXD/APDQGg/9Pf8A36/+vV3w98YdJ8T6vFY6V9oM8wYrvj2jgEnn8Kn2cux6EMywtSSjGqm35nV0UVW1PV7fR4hJqU0cKHoXbGfp61KV9jsclFXbLNFc3P8AFPSYZNoklb3EZH86v6V4103WWCWN1G0jdEOVY/QHrTcJLVoxjiaU3aM0/matFFFSbhRRRQAUUUUAFFFFABRRRQBT1z/jz/4FWPW9fWn22HZu285zjNU/+Ef/AOm3/jn/ANegwqwlJ3R4X8WDnx9f8/8APP8AD92tc3IQq7nIUDqTXsniz4DP4m164vk1RYfP2/IbfdjCheu72zXwJ+3j+0t/wqPx/ceFPhlrcWtalp2U1CZbXy4bKQ/8slO873H8WMbTxknIGWMzOhltL21eVl97fkjy8i8POIeNcz+oZPhvaTldtuUYxjG+spSb0ir9m3sk3ofRy6raM+1bq3LegkH+Ndp8DSG+JVgRyCkv/otq/KKL9p7x3Dei4Gv3DsDnYUXafbgZ/WvtT/gl5+1PY/FXx/HpXj3WItO8SQq5tbF4QsWqKUIJik38OuclNuSBkFudvBgeLMBmU/YxbjJ7cy38rpvU/QeI/o6cbcCU4ZnjKVKtQi05yozcnBdXKM4U5Nd3FStu7I+/9Uv/ALBbkqRvbhc8815D4pvbiHWXHiCdXnflWLYDDtt9B7VwH7WX7c8Hw38SXGg/DuO21HWIP3dxLI263s27qdpBd+uQCMdznivnLWv2qfHPi6RRresh41fcsa2sSBPYMF3Y/GnWz/C4KpyO8mt7W0+9r8DuwfhDxFxRgljKMY04PWPtJNcyfWyjJpPo3butHc+wYpRKuVoZSxBBwRXzN8O/2rdSh1K2tdcitDFJ8jSYblvfnj69u+a+h/CniCLxHp4nt+CQCR6V7+FxVLGU1Vou8X/WvmfjucZTjeHcwnlmYUnTrR1s9U09pRa0lF911TTs00ekfDvx7I90un61IXLcQyseT/sn19jXeV4dlo5FeDIdTkEHkEV7NoeonVdItrhhgzRq5+pHNZ14KLTR7OWYmVWLpzeq29C3RRRXOeqFFFFABRRRQAUUUUAcd8b9YutD8HpPpE8lvN9oVd6HBwQcj9K8k/4WVr//AEFbz/vuvUv2hP8AkRE/6+U/k1eJLk8L3oufEZ/WqU8VaMmtF1OoT436joPhHXWv7qW4vLbTri+tS5zl4oy2z3yBn8DX47atf3GrancXmrTSXF1eStPNK5y0rsSzMT3JJJr9TPF1jJeaSxssedCd67hkMO4I7g9x3GR3r85/jx8FtR+DPjF7TUoJhpd+Dc6XdMMrcQ7um7pvQ/Iw7EZ6EE/D8aYepUhSqr4VdPybtb7z+uvogcSYNYnMspxMksTNQlC71nCPPzJd+VtNrs0/s6eeOu1sV1fwz8IzprFrqxmntTZyLNbNE7RyeYpBVwwIK4IyCDVLw34eF/Ms1+P3SnKr/f8Ar7V3NlN5Y2joBgD0r4WhTtJSZ/bGa42TpuhDro/TsdVZXbTu7yMXdzlnY5LHnJJPWtWzlxkZ+lcvp9xk/Kck9/zrbtJu4NehGVnc+CxFFR0RuRzGUf55r7C/Z0tL1vANpd6xFLH9oiUxmRSPNGBlhnqM55+tfOv7MnwevPjR8RbSGO3c6TYSpPfzEfIqg52Z7s2MY9MntX6D3nh+HUNKWC4GCB8jjqh9a/ROFPaUqFScvhk1b5LV/j+B/GP0g4YPMc4wcKMl7ajCanbtNxcYt91aTt/ev1OCPI4OK9c8FwNb+GLFZOG8lSR6ZGf61wWi+CLi68QC2u0PkxkPI+PlZfY+p6V6giBFAQYA6D0r6WtU5tD8XyqjKHNOXoLRRRWB7AUUUUAFFFFABRRRQBzHxe8OS+JvBVxDZZM0JE6KB98r2/In8a8AcjPyV9TV4L8YfBo8KeJ3ktUxa32ZYyOin+JfwJ/Iig+U4kwd1HER9H+hyZUbju+X9a5/4jfDrw58TPh1feG/iPYy3GlzObi2uLdQbjS58Y82LPY9xnpnggmt/kL7GgAscLyTUzoxrxcJq6e54GWZnismxdPHYGo6dam7xktGmj84fHXgO8+Gviu603UFZ4oZGSC42FFuFHRgD0OCMjJxnuME17SX5ee9frR4r/Y+8L/F34Gt4X8d2Sxy3LG8W6iUCexuWGPMjPYgALjoQMHrX5ifH/8AZ+8Rfs0fEGfQvHkG5GzJZ3sanyL+LPDoexGQGXqp69ifzPO8kllc3Upq9J/h5P8ARn+lnhH4qR46wNPB5q4wzCMVzJaKp3lBdGvtR6brTbGsbjcBznFer/s0/s/a7+0b4zGn+F0MFjakPf6g6/urVOw93PO1e+CeACRwfwY+FOqfGTxPHY6DEyQRkG4uCMpCv9W64H9M1+lXwNNv8E/h7Z6F4Q0qwtLaBQWIDeZO+PmkkYnLMf8AADAAA68gyWWParVNKa/H08vP7tdvnvF3xcwXCDeVYGaljWtbaqkns5f3nvGPzelk+0+FnwTsPhB4SttH8JWscdvbr8zbhvmfjLue7HHX+gArqrfRHd/3zKAPTnNch/wtq8/59bX/AMe/xqQfFi+Y4Fta/wDj3+NfosKfs0oxVktj+MKmZU8TUlWqzcpybbbu22922d7b2y2ybYhx/OpK89/4Wze/8+1r/wCPf412PhbV313RIbq5VEeXJIXOOGI7/Sk00bUMTTrPlgaNFFFI6AooooAKKKKACiiigArm/in4QHjLwrLBGB9ph/ewHvvHb8eR+NdJRQZ1qUa8JU5bM+WZYnglZJ1ZHQ4YHgg+9dV8HvCB8UeLopLhCbWxImkJHBI+6v4nn6A17BrPw30TxBd+fq2nwyzd3GUZvqVIz+NaWkaJa6DaCDR4IreEdERcD6n1PvV8+mh8zhuHZUqynUknFO9u/a5arhf2hf2ePDn7S3w/m8P/ABEty8ZPmW1zHgT2MvaSJj0Pt0I4Nd1RWU4RqxcJq6Z9ng8ZXy+vDE4abhUg04yTs011TPmvwR8BtC+Bol0jwbbmO1tX2q0h3SSnAy8jd2J5/wABgDqKw/iPcSR+N9SEbsP356GqPhueSXxBYh3Yr9ojBBPB+YVvGMaUVGKskfB4jMKmJxVSrWblOcm5Sbu229W29WzqPL96c0gC/J19a9E+xxf880/75q7odhC1y2Yoz8v90VLlc9aGX3dlL8P+CeXuu2M16f8ADk7vCFofUN/6G1a/2CD/AJ4x/wDfIp8caxLiNQo9BUt3PQw2D+rycua46iiikdoUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB8/wDxE0S6uPG2otHExUzMc8VS0DR7iz1qzkmiZY450ZiewDAmuy8af8jRfZP/AC1NZ8UXmnL/AP66bdz46WESquSfW/4ndHxJYDrdJ+Rq3pni/TbaZmlu4wMYzg/4VwNRyMWbatI9eOLnDZHqA8eaS3S8jP4N/hWlYX8Wp2qTWTiSN+jDvzj+leQKoX7telfDv/kUrX6N/wChtQdmFxM603GXY26KKKDuCiiigAooooAKKKKACiiigAooooAKKKKAOV1b4XR6tqU1zJeOhmbcQI+n61D/AMKjj/5/5f8Av0P8a7Cig53hKLd3E4//AIVHH/z/AMv/AH6H+NIPhFGowL+X/v2P8a7GigFhKK15Tjf+FQp/0EJP+/Q/xrpfD+jjQdJhtVkMoiB+YjGcknp+NXaKDSFKFN3igooooNAooooA/9kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/bAEMAAgICAgIBAgICAgICAgMDBgQDAwMDBwUFBAYIBwgICAcICAkKDQsJCQwKCAgLDwsMDQ4ODg4JCxARDw4RDQ4ODv/bAEMBAgICAwMDBgQEBg4JCAkODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODv/AABEIAoACegMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP38ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCLHy4rC13WrXQPC+oardgfZ7SAysfpW3n5fauN8a+Hz4t+GusaHb3P2W4vbYrDN6GqTOXE+39j+53OOi8bahp/wAFLnxb4qsILeSXM9jpsA/f7SMwQc9Zz047/SvQPDNxrk/gu1n8QwW9tq0i5uIbc5WLOeM968aPwx8V3n7Odz4V1XxHb3XiH7b58F32g54H869X8D6Truj/AA207T/Eeq/21rMQ/wBIujxk1s7Hj5b9Z9v+/Ol1K+Fj4fvr7tDb+bj8D/hXA/C3xvceOvg1pniTU7e2065vTL/o8JzwD/OtP4k3n9mfs/8AjDUP+eGkTn/x014T8N/gN4F1r4E+F9V1NddGo3umwTXDQajPAM4z65rnPoj6s8+3/wCe0P50vnw/89v1rwf/AIZx+Gv93xP/AODqf/Gruh/AbwHoPivT9c09ddbULK4863afUpiAfcZoA9yryz4oeOT8Pvh/Bqdvp/8AaV/cahDZ2FiDzOSen8/0r1Ovkqy8Q2XxR/betYPNWfwt4RtpprZc8T3H/PegD1rxr48vPDms+BtIstJtrrWfEOpCA29xP/qYRgzH3xxXpf22x/5/bb/wJFfLVl4e0r48fHHxVrutw3Nx4G0T/iV6L5FwYfPn/wCXiepYfg58CpPjFf8AgiLStbGu2enLe3CG/n8nySQBznHegD6liu7eYfuZ4W/GrdfIXgT4f+G9F/be1H/hENHutM0jw/puLmaYzk3FxcfXivdfG8fxJkuNPPgO98OW0H/L1/aqMfyxQBX8AeNb7xVqvjO3vrG3tRousmxgaBuJhjrzWP4l+Nngrwr42uPDmqHVTqMIzP8AZrEzD9K+f/hVcfFXUtU8dz+E9V8IGZtaMupfaFJE8/fyewH14rtdN8X+GvCf7bPxCufF2r6Xown02whHnnrP9aAO0/4aO+Hv/Uy/+C3/AOvXpPgnxtoPjjwtPqnh77T9ginMP7+3MPI9BXMf8Lp+EP8A0OWg/wDfX/1q5D9nGaCb4Y+KLm3/ANTN4oucfpQB2OofE3SvD/xptfBviDTtQ0WG9wNO1a4A+z303dQfWtvx745sfAXhKHU77T9R1LzrgQQW9imZmq54v8I6H458F3Og65b/AGm2m9uYa8P+PNlF4f8A2ffB9jFqFzb29lrljAL+ebzrgDn8zQB0WpfHK30a2gn1P4ffEDTYZ7jyLf7Tpvkmeb86nk+NcFlfabb6r4G8f6ML25hsoJ9R0zyIPOOeM5/zivnv4ga/oV7oXh5rL433Hiww6zbz+QLe3/cdf3/+fWrPjTxBpGp3vg23sfjBcePrj/hI7D/iXi3t/wBx/pH/AB8UAfd80whtDKRkV49/wvj4Uf8AQ4/+U25/+M17RXz78UvEur+GfGngvQPDp8JacNbNwbi51iH/AEeDyPs/p9aAK3i39oXwZpXgC5vvC2oW2uaxj/RrC4t7i38/8TBWzZfHj4ay6TBNeeJTa3HkbriA6dcHyP8AyBXkvjDRfFnjDw7b6Tqvjz4IW9tBc+d/o9yYa6K68RfEKz0m5nHiz4DXHkW/nfZ4Lg0Aev8Ahz4o+BvF/iY6RoGujUNSFv53kLbzQnH4ivS68s+E2v3Hi34HaD4rvrOxttRvhMZxbw4H+vYY/TNW/Hdv45n0zT/+ED1vQ9GuIXBvzqNvuHk+3pQBm+HfGWqa/wDtHeNvDP2a1Hh/RbeACfP78znkitTx18SNA8AWlhPrMOtXAvDiD+z7Xzzmvk7wLF8X/wDhX/jH4keHvEvhqC3v7me91EXFqSJ/IB/1HoOvWvrD4Wa3q3iX4AeHde1yf7RqN9aiac/Z/I5PtQB55/w0p4H/AOgV40/8Ff8A9eu98B/E7w18RF1f+xLfVLf7EcXH2+28g1g/Erxxq2k3ejeDvBtmtx4v1/IsJs/uLaLvOfpXR/D7wLY+BfAaaZbs91qE/wC+1C/mP764nPc0AcL8S/Gvi/wn420A6XpUF14XlaEalceTyhM2CB6cH9aZ4j8c+L9C+Pnh3S10q2k8Iajcw2zXZ67pSR/MV2viHwre+JPH2kNd3toPDNmPONjg+dPMM4yfQVXvPB15qvxhsNZ1TUIBouljzdO0+DOfPP8Ay2m/XGK6ro+Vr5fj3Xuj1iiiiuU+qCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAOb8S+HrDxX4A1Hw3qhnNhfW/kXHknHFeI/8M1eB/wDoN+Nv/Bp/9arV18BvtGqXNwPil8TbYzXPn4g1kik/4Z/P/RWPit/4Oj/hQAf8M2eBv+g545/8HR/wrlPB/hOx8Dft2QaFpN9rl1p83hwzYv7rz/1rstM+Bp03xDp98fij8SbryLjzjBPqmROfQ1X03F1/wUX8RdxpnhaD/wAeP/16APUPHuj6r4l+HF/oWi6smjX17mE3XcQkgS4/AkV4X4R8KaH4Y/bTvvCulWxTT4fBqwEH/luCRmvq6vnRZI4v+ChniCaXiGDwcpP03An9KAL95qp8JfHXwB8MPANhpmn6bOJ73WLdYf8AU2/t6Ek/yqjpX/KSzxb/ANidB/6Ogpvwhhl8WfEvxn8VdTtp7YX1z9h0hZ+CLeHPP5/1pdK/5SYeKf8AsTIf/R8FAHQfCzxZrOtXnjHw/wCK5rNvFOh6wYZ2t7byBPAf9Qfxra+KXiSTQfh0bPTCv/CRa1ONL0iMnrPN3NcNru3wn+3f4Y1Qcad4u0/7BdZ/57wcwfzr1G88JaTffFbR/GF5582o6bbzQ23P7mEHqcevWgD5I8AeDNa8PDxXrngs3Nx4h8MeITZmA9NWtxj9xXp2jz+Gh+3B8TP+En/sO3P9mWO0aiYK6L4H/wDI1/Fv/sbZ65Wz8I+G/Fv7cnxLtvFGkWms28Gm2M9t9oGcUAezfaPhb/z28Af+S1ecfs5eR/wrfxT9n/1P/CT3OP0rrv8AhSPwm/6EzQvyrkP2cYbeH4Y+KLa3P7mHxRc4/SgDn/jJ8LvCOmfCLxn4xsoNTGukfaPP/tKfPnetbniXxF4xs9e+FvgvwqfDguNa0h5zPq0Bm/1EMJ6A9eeta37QGvaTYfs6eIdJvr+3ttR1S18jT7cH99OfauWmb/hJvjF8FNX0GeebTBo19ANRt4P9RN9n70Acp8StL+KH2bwZB4huPh+RN4htxbGwsLiEefz/AK/n/UetbOseKfifo/g/xRrtvqHwr1M6BN5OoQW2j3HnwTce/vXVXvwT17WRp3/CUfFjxdrf2K4+0QeRbwW+JvWvJvGtlYeGP+FmeGdKn8c63qOt6dBBc29xp1xcfaJ/+fjz6APsTw/eS6n4N0i/nAW6urGGab6kAn+Zr57+OFtPe/Gn4TW1tpmi6zcH7diw1fH2ebi2/wBdXtUEmsaN8GbE2el/2prNnpEGywE/k+dNtAIz25Br508cW/xA8ZeLPC+r+IPg+G0XRjObnT7jW7c/aPPAH9KANT/hGNX/AOiP/s9/+BA/+R6zdR8L6wPC+pH/AIVP8BbcG2n/AH9vcfvx/wCS9YukaLpGs6YL/RP2dND1HTz0nt9aHNYmq2Og2erf8I3L8BfDej+Ib6Am2t7jxGPP/wCu/T/6/vQB9Ffs+f8AJoHgr/duP/SietX4ya+PDX7O3ivUIQDc/ZRBD7Gf9wP51518Lrn4keEvBHhjwZqnw5uRY20vk3Or/wBpQHH7887R1r6Qu7a3vbKW2u4YJ7aUYmhm5BFAHzB4insvBn/BOvT9K0q8ttQnvtMhsILiA/8AHxPOf339a6m+0b4v+H/CXg7Qfh3/AMIp/Z1josMGojV8588dcY5r58vNG87426vqvw00PUvEXgbwzqMF9cad9p/0e4uP+nevs7wT400Xx14Mh13RrjNvnypoJRzDMOx9+aAPlPXP+F3/APDS/gv+1P8AhEP+Eq+zT/2d5H+o8j/lvnvmvffBH/C7f+E4/wCK+/4RD/hHvsv/ADD8+f538qyfGH/J93wq/wCwbffyr36gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACsu8gnm0y4gt5/ss5g/cT4/1JrUooA8D/AOEU+OnkfZv+Fo6P0x5/9hQ+d/hXS/Dz4cweBrjWb+91a68ReIdUuPP1DULnqa9XooAK8ntvBV/H+1VqHjs3Fp9gn0YWfkY/f5BzXrFFAHDeL7LxneeHIYvBGt6Zo2pCcEvfWvnwmHvx1zXC+BPhx4q0r4uaz468ceJdN1zWrzTxZYsLXyIBCCCP5V7nRQBRktbea6hmlggmnhbMJI5iq9RRQB5d8PvBd/4U1rxvd309tcLrWsm+h8jsCO9cJrHwQt/FHx/8R+JfEGoXJ0i9toRbQWFwYJgR6mvoyigD5/8A+Gc/Af8Az/eMv/Bwf8K6D4TeAr34f/D/AFHQb6+trkTalNPbmAY/cnoK9gooA8m0z4c/8X91jx54hv11q5YeTosEsAxYQ9wKxdT+ERtvE1xq/gPxnrvgS6u7jz7uC2xPbT/9sDgV7nRQB4T/AMIP8Yf+iwt/4JIKP+EH+MP/AEWFv/BJBXu1FAHM6BYapp3gm0sdW1X+2dYSD/SL/wAjHnmvIl+D/iLxNdm4+KHjvUfEUB5bR9PX7PYfl1r6DooAxNH0bSvD+gW+k6TY22m6dB/x728HQVneIvBnhnxbpf2fxDoem6ov/TxBmusooA8V8J/D7xL4O8cQjSfGuoan4F+y4Gj6mDcTW5xx5M/pXQfEfwvrvjLwONE0TxD/AMI4JZ/9OmC5M0GOQK9KooA5Pwp4S0jwb4KttB0O3FtYQDp3lrP1zQNUbwjcWngrUNO8JalLcecbj7BFMOT+9+U8E+/rXeUUAeC+Hfhj4t/4XRp/jLxr4ztvEdzptqYLaC200W4Ge9e9UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUVDxEPWmfa7f/AJ7LQBZoqDz4f+e360efD/z2/WgCeioPPh/57frR58P/AD2/WgCTj1o49aq+fH/z1H51nf2/pX/QQt/zp2Of6wbfHrTcj1rI/tvSv+f+2/OrkFxDd2wmgmWeE9COlFgWINCiiikdAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAZ93/yD6zD90Vp3f/IPrMP3RW8TmxI+iiimYBRRRQAw/dFeWH/j9avUz90V5ZN/x+NVYY8zMhP4TXqXh3/kTIPpXlv8Jr1Lw7/yJkH0oxBOSfx2dLRRRXKfShRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBn3f8AyD6zD90Vp3f/ACD6zD90VvE5sSPooopmAUUUUAMH3q8sX/j9Nepj71eWL/x+mg8zMhP4TXqfh7/kUofpXln8Jr1Pw9/yKUP0qsQRkv8AHOkooorlPpgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAo3f/AB51lH71at3/AMedZR+9Qc2JEooooMAooooAUferyxf+P016mPvV5Yv/AB+mug8zMg/5aV6h4d/5EyD6V5f/AMtK9Q8O/wDImQfShiyP+OzpqKKK5z6QKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKN3/wAedZR+9Wrd/wDHnWUfvUHNiRKKKKDAKKKKAFH3q8sX/j9Nepj71eaL/wAfproPMzIr/wDLSvUPDv8AyJkH0ry//lpXqHh3/kTIPpQxZH/HZ01FFFc59IFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFG7/486yj96tW7/486yj96g5sSJRRRQYBRRRQAo+9Xmi/8fpr0sferzRf+P010HmZkH/LSvSPDv8AyJkH0rzf/lpXpHh3/kTIPpQxZH/HZ01FFFc59IFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFG7/486yj96tW7/486yj96g5sSJRRRQYBRRRQA5u1eZt/x+ivTG7V5m3/AB+ig8zMg/5aV6R4d/5EyD6V5v8A8tK9I8O/8iZB9K6GLI/47OmooornPpAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAo3f/AB51lH71at3/AMedZR+9Qc2JEooooMAooooAdyTkV5FLqVj9r/4+PrXrp4XOa+eJxi6uq6D5rPMSdX/aVgQP9IrtdJ8WaJZ6Db2818DNjr5JFePdO9HOODQebhczxOHPcf8AhN/Dv/QQb/vxN/hR/wAJv4d/6CDf9+Jv8K8Oz/tfpRn/AGv0q/q/kdP+s2IPcf8AhN/Dv/QQb/vxN/hR/wAJv4d/6CDf9+Jv8K8Oz/tfpRn/AGv0o+r+Qf6zYg9x/wCE38O/9BBv+/E3+FH/AAm/h3/oIN/34m/wrw7P+1+lGf8Aa/Sj6v5B/rNiD3H/AITfw7/0EG/78Tf4Uf8ACb+Hf+gg3/fib/CvDs/7X6UZ/wBr9KPq/kH+s2IPc/8AhOPDv/P4P+/Z/wAKb/wm/h3/AKCDf9+Jv8K8Oz/tfpRn/a/Sj6v5B/rNiD3OHxp4enuYIYbxczdAIjz+ldXsVuhr5q03jxDp3p9ogr6WHyR5/Ks2fRZJmNfELUt0UUVge4FFFFABRRRQBXDZBFOKg1y954lsrNvJiPnz+grl7vxLqsqgEfZ/+uBzXQsO+x5tfMsOj0uSeCJcyyY+pqhLrWkwjm8tlP1ryyZZ5v8AXz/aar4FV9WPO/t09P8A+El0n/nsf+/Zp/8AwkOk/wDP6PzryvI9KMj0p/Vg/tPEHskN7YTD9xcW7VeyPWvD8n0q/Fqd/aDEM1wR6Gl9WZ0f20j2M/SmcVwFn4tPS+gx6fZ+a7G0u7a+tN0EwJ71zJnoYbFUK+xqUUUUjrCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAo3f/HnWUfvVq3f/AB51lH71BzYkSiiigwCiiigB3/LSvn+b/j7uP+vmvoD/AJaV87z/APH1c11YY+ZzwdRRRUnzoUUUUAR0UUV2AFFFFABRRRQAUUUUAW9N/wCRg0//AK+IK+nB92vmPTf+Rg0//r4gr6cH3a5MSfacMf7uS0UUVzH0gUUVj6lqX2LSvtAg+0UAO1DUrfTbEzzE7a821HV77Uj8v+jwd4O9UJb2a9u/Om/4+PSoAe3St0rHyeJzP25LRRRXaeWFFFFABRRRQAUUUUAV6nhmniuvPhnFvcfzqCig7D0LSPE32gfZ74eRPj/XHoa653214jg4rqdC17yT9hvB+57GuX6t5HsZbmTa/fnptFR1JXKe4FFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFG7/486yj96tW7/wCPOso/eoObEiUUUUGAUUUUAOP8VeAz/wDH5dV78f4q+eJ/+Pu7roPmc8FooooPnQooooAKKKzptUsID/r6AL/y0fLXPTeIT/ywtv1qD/hIbn/n2tq7Dk+s4Y6j5aPlrlh4huP+W9tWjDrUH/LcXNtQH1nDGtRVeCeCb/UXFWKDrLem/wDIwaf/ANfEFfTg+7XzHpv/ACMGn/8AXxBX04Pu1yYk+04Y/wB3JaKKK5j6QqTSiG3yetY01E0/nXdV63SOc5bWNMEH+kQD/R65/wB69L87P/6q4PXrG4sz59lb/wCj/wDoimfNYjDGdx60cetY39qS/wDPvViDU7b/AJb2/Ndh531k0KsVnQTwTf8ALxVmgksUUUUAFFFFABRRRQAVXqxVeg7Ds/Des5b7DPgH/l3r0EDgj1rw0d+a9R0LU/7S0zJOLiIgTg+tcmIR7OWYn/lydLRRRXMe2FFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAUbv/jzrKP3q1bv/AI86yj96g5sSJRRRQYBRRRQAo+9Xz1L/AMfVzX0KPvV89S/8fVzQfM54FFFFdB86J0FZ13qcEP7gH7TcVjahrPJt4biuL1LxDY6Xa/v7j/Sf+ff1oPMxOJ+rnQz3txP/AMfE9c9d+INIsh/r/tP/AF715D4j8aQQWon1W/8As1t/y7W9vXiup/Eq/uY/I0a3toD/AM/E/H868bMuJsuwB974feB/GfGv7/A4f6vQ/wCf9c+ppfGgwPJsf/Ais7/hNL/Gf+JZmvi298Qa3fA/bdYurjP/AE3NZqiR13S3H/jgr5z/AIiB/wBQ5/SuWfQYr/V7YzOb/wDcBf5n3JD401D/AJ4W1z71t2XjSwnH7+3ubavgWCeeAEQXF1b/APXvcV0OmeNfE+mdb06n/wBfBrowvHGH/wCX+HPIzz6Dmc4f/kVZj9Y/7CD9AbO+gvW8+xn+0eprorTWriEjzz9pr4n8OfE3TbyW2ium/sab/n5xXvejeNDk22q3P/bxivtsszLD4/8AgH8qcWcJcQ8J5gsFnWH9gmfSOjTwT6tpog/5+IK+mTzXxV4avc+KtGuIbjibUYP/AEor7WU5TmjEH13CGIvhiX/lnWZdziIiLuRWn/yzrlrybF559c3Q+kxAuMEc1VmngznNc7rHiGx0TSLi/wBWv7XTtPh6/aK+afE/7Q6R3NxD4ZsdpP8Ay/3+T/SubEZjh6Gx7PDfBOcZ4r4PDn1j9tyarT3uOotvbivzz1X4geMdZP8ApniTUAP+eFsPIrmPPuJgfPnuLjPvXzj4v/6hz9Zwn0fcS1+/xB9v+JIZ9Mf7dpX2a507/l5t/wDnhXFQeIbf/lvb18tW095AQIri5g/StWy1vV7P/U3/AP4EV0Ybi/8A5/4c+czr6NOJa/2HMD6rhvre9IMFxmtmC8uIAR61816T44tZU8m6h8gf8/NuMV2//Cx7DSz9nnuP7S/696+tw2ZYfH/wD8C4t4bznhqvfNMOe7QTwS/6jirRPPIryCy8a+dZi4sbeuz03xbb32YJ7f7Nc11Hi4XM8NiDqqKrQXsE3+oqzQeiWKKKKACq9WKKDsIf+Wla2h3hs9bhxxBP/ryexrJ/5aUn8JoJwx7vRWPoV59u8OQT+orYryz7YKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAjqL7JB/z7w/981ZooAq/ZLP/nhD+QqL7Fb/APPC1/8AAer9FAGQ1jZZ+WztwP8ArhXyf8e/jt4f+HcMmi6JZWGoeLp4PlBgBEHTBm4zivQPj18V4vhl8IHvoMT63eZisLcfxNkf/Xr8eNS1G+17XrnUtSuLjUL+8uPOuJ56+V4jzv6uvYUtz9/8EfCOjxBN5pjVbDr8X/kW9X1TUtY8Rz6zqt4t/eSD5ZgKyGBPFXOvfNVupr8u5ne5/d+Epxw0FFKyQlFFFI7gqvViigClLK8eNoyK9++Cnx61j4bajBpWo2f/AAkPhCb/AF9jNB/pEHXHke1eCq6v0OTS/dB966sLisRh/wB/QR83xLwvl3EGXvBY6jdM/eLwtrHhPxZ4Nstd8O/2bf6VMBNbTQQ8HPcHFdhG4aJmAxivxa+B3xz1z4WeNQ6G41Dwnd/8hCxHUHn9/DxX7BeE/FOi+L/BVlrmg3dvfaVeQCWCeFshhzzX63kecRzDD83U/wA7/EjwwzHhHMeSWtB7P+upsXEq21nLJ7da8V8e/ELSfBeg/bb1ftOoTD9xYZ/19b3xT+I2l+BPCA84LcajMP8AR7LPM/t0r86Nf8Q6p4q8UXWp6lcfabibHb/UVlnGdPD/ALmludnhp4a189xH1zGfwF+JpeIvFeteKNbN9rM4/wCne3A/cQVjRn5M96plefWrP3RXwzdz+tMHgsPhqCoUNEi1UlR0VBu1csVYqvViL7v40HIyEFmHAp5ZRkk8VE9xGvBOD9DThsliyPmWurC4j6v/AAT5/OsmwuYYd4fG0L0TX0fVLjRdXFxBxb/8vNvXstle+fZW1/Y3HFeArIizLAW+c528fjXY+FdTFjq32Cf/AI956/T8jzL6/hz/ADj8UvDbEcF5z/s7/cV/4B9E6be+dafaIP8Aj4Fdlpt75/7i4/4+TXkOmXv2LV/+nc13kM/kXnnnvXpnz2V4k7qiiD99aUUH0oUUUUAV6KsUUAdl4RnG2e3Pf99+dd3/AAmvNPCsu7xSB621elV5lz6LLP8AdySiiikekFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBg6nqdnpGktNduFgHcisUeONFC4M1xj/rif8ACq/j8AeC8/8ATcV4t7mqbPk8zzPEYfEHuH/CdaB/z8Tf9+T/AIUf8J1oH/PxN/35P+FeH5HrRketHMed/buJPcP+E60D/n4m/wC/J/wo/wCE60D/AJ+Jv+/J/wAK8PyPWjI9aOYP7dxJ7kPHGig/664/78n/AArR03xLpOqi4FnMH8nhq+fD+dbOj6l/Z2vwX3S2I/0mlc6MNnmIZ799rg35zVOTULG3B5wTVIfvjjvXkPxU8SHwt8EfE2uD/j5tbDMH51hicR7E+zy7D18dmGHwdH/l+fnN+0L8QD47/aA1aeKf/iU6aBZ2PHU8ZNeIqCADSMm4qD2pScLmvxLFYr6xifbn+qXD2VYfJctw+AobIKKKK5j6Ar0UUUHYFFFFAFeirFV6AGOdpDKOa93+BHxa8U/DnxTPHpcP27w5MD9usppx5Pn/APPcZBrxnRdKuNS1f7PDzb/8vE9eu2Nta6bZ/Yoz9kHrjNenlTxOHxXtz4fjOGXZhhHgsRQ9uvyOy17xDqfibxbNrOryiaaUYAH/AC71kCLk55qCMfLnNTySeX9K3u2z5TC4SnhYKhRVki9UlR0VIiSrFV6KBNXNCio6krsOVqxcoqvVig5hvRsUnp2FDNiIn0psbbowete1kWJ+r4i5+SeNHCSz7hbEYc9p0G9N94et7k/6+vTdMnE+l25rwnwTOR/aMB5/5b17JoM+bO4tq/WcSf5w5FiT0zTf+QXBWjWdpn7nSretGsD7UKKKKDsCiiq9AHQ+HP8Akcov92vUP4TXmHhr/kaIfpXp/wDCa5MQfRZX/u5PRRRXMekFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB598QP+RHf/AK6ivFz92vaPiB/yI7/9dRXi5+7TZ8Dnn+8i0UUUjxQooooAKsVXooA7fwJrf2uwmsLjAnszj/tjj/8AXXkH7VN75P7JurD/AJ738MP6irmj6p/YvxB+3/8ALt9p/wBI/wCuFZf7VMH239kO9uIekN/DN+orz87/AORdiD9f8EcV9Y4qy72//QQvzPzPqvViivxs/wBaSvRRRXOAVXqxVegAooooOwf3q7p+mT6jcmH/AJdqNN06bUrr90cCvRLOC3srPyIOorfC4Y8HM8z9hotyxZ2cFlafZ4P+PetCq9WK9E+TkXKKp1coOUuVJUdSUHLIsUVHUlBiXKKr1YrsOckoqOpKCGrE8f8Ax7D/AD3oi+6aI/8Aj2H+e9EX3TTw/U8nMf8Ad6x1/hDH/CcZ/wCnavd/CsP2jxEbcdK8q+G3hLXtf8b/AGiyt/8ARof+Xi4/496+qrPwl/wj1p9osrj7V/z81+04g/yd4YyzE/xyaiiiqPtwooooAKKKKAOj8Iwj/hILmc9IrcCvSB92uQ8IW/laFPP/AM9mzXXj7teYj6nDfwES0UUUjrCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA8++IH/Ijv8A9dRXi5+7XtHxA/5Ed/8ArqK8XP3abPgc8/3kWiiikeKWKr0UUAFFFFAHJ6nAYtYucVT1NR4y/Zq+Inga4xc6jZaeJ7f/AKeIDiet3X7c/wCj3HU1wY1O48L/ABC0bxNBxb/6jUj/ANMKMThvb4cjJM7xOQ5zh8d/0Dn577tuMnAoA/ebvWvRPjP4LbwZ8cNYsICDo14ft2kTD/njPg15w7bYya/DMThfq/7g/wBq8hzfDZhl9DHUdq46q9WKr0j6AKKKK5wK9X7S0nu7gk9KLSzF3d812lnbiK18iHrXScuLxXsNFuWLOG3srT7PBWjVeitz5U0KKgg61PXQc5YoqvVighqxcqxVeig5WrmhRUdSUHK1YsVYqnUlBi1cuVJUdFdhztXJSc5FdB4K0oax8SdG0k/8trisAjjNfRHwG8Medq2o+K5iBBB+5tx/03r0chw31jEH574h53/ZHD2IxB9VaXBBDnyLe2trb/p3rag71nW0H+iGtGDvX6efwxhjlNS0ryP9Ig5tqxgcfSvTPeuM1jS/IH2i3/49qDlxOGMSiiig88eDkUkMHnXf2fP4Uo5HPeun8L2XnT/b5usPA96DfC4b6xiDtrS3FnpMFv8A88RWhRRXOfWhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHn3j/AP5Es/8AXZa8XP3a9o8f/wDIln/rsteLn7tNnwOef7yLRRRSPFCiirFAFeiiigCtNCZrO5t+9cFd2XnWtzYT9q9F6dO9Yus2PH2iCg5cywx5P4g8FXHxN+BFx4ZPPjnwj++0b/p4g/54V8FTQSafPcwT2xt5oj/qJ+3+c1+lemzf2Z440/XoP+PmH/j5/wCniCsD4/8AwJt/Flpc+OfBNsP7eI8/UbC3/wCX/H/txXyvEmR+3/f0D+vvox+M31DDf2Lmn8Hv2/4B+fdFA/c/uJ6K/NT/AEMK9T2dnPNdZNLBB595XRQQCEeRCPwoFicTbYuQwiG0/cVeqnViug8Nq5YqSo6KDnauXKKr1YoMCxVis+rFdBzNXLFXKp1coOQuUVXqxQc5YqSo6KDnJsgEkmpdwPQZqs7ZbFaejaJquv69b6RpcHn3Ew5NdmF/fnkZli8PgaDr1jW8K+H9Q8TeJ7XSNMgzdTdT/wA8K/QPwp4esfD/AIU0/SLE5t7KuV+Hnw+sPBnh0wQH7VrU/wDyEbjFerQweT7Cv0fI8t+oYc/irxJ43/1lzBKh/AHVoVBB1qevZPgyOiiiucDltS0ryP8ASIObaueBx9K9M965XUtF/wBK+0WFdB5eJwxi2dnPd6rBDCeOteqWcMFnZwW8PQ1naRpi6baHd/r5etb9YJHpYXDewJKKKKR6QUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBwPj/wD5Es/9dxXin8Rr3nxfZS6h4SuIYCBcR4lUfSvBv4jTZ8Tnn+8C0VYopHzpXooooAKKsVXoAKKKKAOS1PS/JJuIP+PavVvh5qn23w6LCf8A4+LL/wBEVyoFZ1nNcaB4sg1axOLb/l5t6CcL/s+JPNf2gfgAviwXPjLwjbiHXyc6hp3/AD//AI/8/FfABS4S+FpKPs+P/wBdft5Zy22q6Za6jZzfaLeXoa+QPjv8CV1pNS8aeELIHXR++v7CD/l96Dz4Dn/j4r4zO8j/AOX1A/uPwQ8cPqr/ALLzT+B/y4f9dPyPhaH9zVuiivz4/s8sVYqvRQcZcqSoofuUtdAnqXKKjqSg5WrFirFZ9WKadjFq5YqxVerFbnNIuUVTq5QcpZ4A9v51LDINuKpNyOK1tG0u91zXoNL0yC4uNQmGYITxXcrHk4zFUMPh/b1nZGj4f0PUPEPiO30rS4PtOozdPavvD4bfDiw8FeHvs8H+lazN/wAhHUKrfDD4cWHgXw4bf/j51qf/AJCNxXr0MPkdOK+7yLI/q5/FfiV4lYjPsR7Ch/AHwQeTViCGiCGrFfRn5iR0UUVzgFFFWIYppRknFdB0EdaMMHk1LHDHCMKMVNWCQElFFFI6AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAi6jHevBPFmj/2d4q/ckeRN++gA7Gvehwua5bxTpH9seFpoIcfaYv3tv9adjzcyw3t8PY8OqvRRSPzkKKKKACirFV6ALFFV6KALFV6KKAMyzu9V8NaoLjTJwbaY5uYCK7yz+I+kz2x+229zp1z7/v65X17VyepaX5OZ7f8A49jQT9axOH/gHiXxx8LeBvEk1x4u8Gana2niQH/iY6f5E58/n/0fXyayiaN45k+U4yM/4V9y694e+2k38HGo/wDpRXgmrfD7VfEOu3X/AAj1jcXGsAefc2EH/LevlOJeGtfb0D+p/o/fSMxFDE0OHeI+v8CueS1YqvVivzY/0JkSVYqvViug5SxRVerFBzklWKz6sUHOXKkqOpK6CZFk4HekD+nNQMP1rX0PSNT8Q+I4tG0iynvr6UZhiY4AHqavCnhYvFYfDYf29fYs6DouqeJPFNvoukWIv9QmGYICcAV+ifw3+D2l+AvDTbpftGv3GPt9/wBwOcww+gq/8J/hPpnw68Onc66hr8w/06+wCT/0y69BmvYhtC4U5z1r9FyXJVhVdn8ceJPiHiM/xHsKH8BfiZUGmTw9/wBaPsc//PEV0OR6UZHpXuH5B9XRgfZ7j/nhTfJn/wCeFz+ddDkelGR6UB9XRlfZJfWkFmP+WxrT3UbqrlNvYobFDFCMLjNWKKKksKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPBvGWj/wBneKRcQD9ze8Nz0NceeoNfQPiPTv7X8KzwcCYgmE+9eED9xd/v6bR8BnmG9hiLlairFV6R4wUUUUAWKr0UUAFFFFABRRRXQByWo6X5A+0Qf8etet/CHwxDD/aHiy4twL+9/c25z0g7VzFlZf2nqlvYQHBnr6MsLG303SILSAbYIhgZrBHs8MZZ/tHtz4p/aF/Z7OvvdeNvBFkv9t9dRsIMD7eBjnr/AK/Pevz9wltF+9GV/wA/41+8jAnkdK+JP2gf2e/+Ehku/Gngu0K68D5t/YQjH9oYA9/9f718bneR3/f0D+zPCPxd+qWyvNP4HR9vXyPgeiq9WK/PD+yGrFyiq9WK6DmLFSVHRQczVyTgDrUofPQZ/GoW7CtPTLK/1PVLewsLf7TPPXXhjy80zKhgcP7asX/Degar4k8TQaLpFkt/fXYJggY4AHck1+mHwl+FGl/Dfws4yL7XZx/p1+cEnn/VdenSvOvg7aeDPAPh9YLaz1PUPEV6f+Jjf/Zc/iP+mHpXu6+NtLUENDqRB9Lev0fIsj+rK6P4V8S/F2hxBifY0HagvxO8yPWjI9a5j/hK7L/nhc/lR/wldl/zwufyr3Ln5f8AWaHc6Xj1o49a5r/hK7L/AJ4XP5Uf8JXZf88Ln8qLj+tYc6Xj1o49a5r/AISuy/54XP5Uf8JXZf8APC5/Ki4fWsOdPketGR61zH/CV2X/ADwufyo/4Suy/wCeFz+VFxfWaHc6fI9aMj1rmP8AhK7L/nhc/lR/wldl/wA8Ln8qLh9Zodzp8j1oyPWuY/4Suy/54XP5Uf8ACV2X/PC5/Ki4fWaHc6fI9aMj1rmP+Ersv+eFz+VH/CV2X/PC5/Ki4fWaHc6yo65r/hLLH/nhc/lXU1J1hRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBF1GO9eN+N9HNpr/wDasOBDL2z/AMtuxr2TPy5rI1jTYNU0K4spvuzDmnY83MsN9Yw9j5zoqxNBPDdXEE5zcQVXpH5yFFFWKAK9FFFABRRRXQAUUVZghnmu7e3g/wCPiegD0D4fabm7uNWnA/54QZ9K9Y6msrTLGDS9BgsYDxCMVrJ3IrFH6bluG+r0EiaiiipOs+GPj/8As/DWre58beDLLGvA+df2MIx/aGMc9f8AXe9fn/xHOYZhkd6/dX939mP8SHqOfWvir4/fs+jWzceNvBcLW2u582+sYRj+0MY9/wDXe9fH57kN/wB/Q3P6M8IPF/6lbKs0fuvZ9v8AgHwVRTR/03p1fnZ/YBOcSITUrEQp7VAzLEvHStTTNLvtW8Q29hpdv9quJ668L+/9Dx8zzLD4HDOvWf7kl0vT77VdXtrO0tzc3U3v0r6v8BeBbfRbQW8H+k6jP/x83FHgLwJb+HrX7PAftOozf8fNxXt9nY29lZ+RBX6fkeR/UD/OTxc8XcRxpiPYUP8AcBLOyt7O0+z2/Suis7IQ/wCkXHSizsvJH2i44FaHuec19Efk+GwwlFFFB1hRRRQAUUUUASUUUUHQFFFWKAK9FFFABRRRQBPb9Vr17+E15Db9Vr17+E1ge1lpPRRRSPSCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDx7x9o/lXkGqwDBm/cT+4rzcdTX0hqVpBqWizWk/3JBg187XVncWerXFjMc3EPf1qmj4nO8P7GumQ0UUVJ86FFFFdABRRRQAg6ccV3Hw/wBMN7r326YAwWfX/rvXDj86+g/D2mf2P4Vt7Y4M2MzH3pM9nhnDe3xHtzpqKKKwPvwooooAKKKKAPhz9oL9nw+Ibe78YeDdPxrufO1Cxh+X+0MY56/6/wB6/PgKumTnzBmX/P8AjX7wHJGQeK+N/jj+zl/wmOrN4o8Fw2sGty4F/ZFvIgvun71jnOa+WzrJfrH76if0Z4R+MX9n2yvNH+46Pt/wD4D0vTL/AF3U7Wz0y2+03M2cCvr7wH4Eg8P232eD/SdRn/4+bivZfD3wd0j4afs96jYWRt9R8QX3kC/vyMZ/fg4PcQdePSrNnZW9lZeRBzXfkeR/UP35+P8Ajf4qYnibMfqNH/cBbOyt7O0+z2/Suis7IQ/6RcdKLOy8kfaLjgVoe55zX0R+KYbDD6KKKD0wooooAjooooOcKKKKAJKKKsUHQR0UVXrnAkoooroAkqvViq9c4Fq3/wCPsfSvX/4TXkFv/wAfY+lev/wmme1lpPRRRSPSCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCLqMd68r8faTl4NUhwD/qp/dTXqY4XNULiCK8tJopQGhlH51SPOzHC/WMPY+as47Ugz2rodc0ebSNR8mX/j2/5d7isGtj4DE/7OFFFFBzhRRU9ray3WpQWdpCJ5pRkknoKAOp8Gad/aPirz5z+5tD5y/WvdBwK53QdGt9H8Piyhwcf645roc/LmsLH6NlmG+r4exLRRRSPSCiiigAooooAKKKKAON8Wf8iDcfSP/wBCFeZ2dl5DCeevWvEf/IpXP0rzY/eFbrY+bzL/AHgZRRRTPPJKKKKDoCiiigAooooAKKKKAJKKr0VzgFFFFAFiiiigAqvViq9ADrf/AI+x9K9n/hNeM2/Va9ppns5bsSUUUUj0wooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAMi9sLLUtNaG6iW4tz1BHWvL9W8A30UnnaVcC4gH/LtcV7EMdqd265ps83E5bh8Ruj5pm0bVof+Piwuv8AwHog02/m/wBRp9z/AOA9fStFI87/AFZw54Zp3gbVr3IvT/Z0HoK9S0jQbDRbYQWcGOOZu9dH070w4700ejhstw+H2JaKKKR6QUUUUAFFFFABRRRQAUUUUAcN40lmh8AztB9792P/AB6vHze6htH7816/40/5J9e/70H/AKOWvFj90V0WPic8/wB4Lv23UP8AnuaP7Uv/APn4rNooPNNL7bqH/Pc0fbdQ/wCe5rNooAvnVL/aP9IrqfCv+m+Ibm3vv9J/0auEP3RXd+Cf+Rguv+vauc6ss/3g7v8Asyx/597aj+zLH/n3tq0aKD64zv7Msf8An3tqP7Msf+fe2rRooAzv7Msf+fe2o/syx/597atGigCK00fT5FJaxtgK0P7F0r/nwtvyqza9Z/8Aeq5VJHQZn9i6T/z4WtH9i6T/AM+FrWvRUnQZH9i6T/z4WtH9i6T/AM+FrWvRQBkf2LpP/Pha1p1JRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHC+Nf8Aknt99I//AEIV4sfuivafGv8AyT2++kf/AKEK8WP3RXQj4nPP94IqKKKDzQooooAlP3RXaeCf+Rsuf+vauLP3RXZ+Cf8AkYLr/r2rnOrLP94PTKKKKD64KKKKACiiigDVtOtx9av1QtOtx9av0HoBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAcL41/5J7ffSP8A9CFeLH7or2nxr/yT2++kf/oQrxY/dFdCPic8/wB4IqKKKDzSOrFFFc4D/wCI12ngj/kYrv8A69q4v+I12ngj/kYrv/r2oPTyv/eT0miiig+lCiiigCSiiig6DRtOtx9av1QtOtx9av0HQFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBwvjP/kn99/ux/wDoQrxjGO/Wve/E0SzeErhZOmK8u+xWHaD9K3Wx8lmeG/2g43n1qxz611f2Cx/54fpR9gsf+eH6Vged9WOU59aOfWur+w2//PCj7BY/88P0oD6scp+mK7TwSP8AifXI/wCneq/2K37QVYsv9DvDPZD7NQdGFw31c9L+aj5q4X+0b/8A5+Lqj+0b/wD5+Lqg9z6yd181HzVwn9pah/z8Uf2lqH/PxQH1k7v5aPlrhP7Tvv8AntdUf2nff89rqg6PrJ6Xa9Z+O/rV6vLv7Uv/APn+ufyqt/bOq/8AP9cf980w/tJHrVFeS/2zqv8Az/XH/fNH9s6r/wA/1x/3zTuL+0UetUV5Z/a+p/8AP7P/AN8Uf2vqf/P7P/3xRcP7RR6mAvY0/jFeUw6vqZH/AB+z/lXqJPy0tzqwuJVfYmooopHSFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHO+I/8AkU5q80P3hXpfiP8A5FOavND94U2eFmH8cZRRRSOAsVXoooAKKKsUASUUUUHQFFFFABRRRQAVXoooAKKsUUAFFFFADbf/AI+x9K9f/hNeQW//AB9j6V6//CaZ6WWk9FFFI9IKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAOd8R/wDIpzV5ofvCvS/Ef/IpzV5ofvCmzwsw/jktV6KKRwBRRVigCSiiig6AooooAKKKKACq9WKr0AFFFWKACiiigAooooAbb/8AH2PpXr/8JryC3/4+x9K9f/hNM9LLSeiiikekFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHO+I/8AkU5q80P3hXpOuwzTeFpoIYBcE9s1wv8AZ17uH+h3H/gPTPDzFfvyhk+lGT6Vf/sy+/58rn/wGo/sy+/58rn/AMBqRz/VSDJ9KMn0qf8Asy+/58rn/wABqP7Mvv8Anyuf/AagPqpBk+lGT6VP/Zl9/wA+Vz/4DUf2Zff8+Vz/AOA1AfVSDJ9KMn0qf+zL7/nyuf8AwGo/sy+/58rn/wABqA+qkGT6UZPpU/8AZl9/z5XP/gNR/Zl9/wA+Vz/4DUB9VKGT6VYyfSp/7Mvv+fK5/wDAaj+zL7/nyuf/AAGoD6qV91G6rP8AZmo/8+N1/wCA1H9maj/z43X/AIDUHV9WKlFWP7Nv/wDnxuf/AAGo/s2//wCfG5/8BqCSvRVj+zb/AP58bn/wGo/s2/8A+fG5/wDAagCGD/j/AD9K9hH3a8mg0y++3Z+w3OP+vevWz90UHp4XYfRRRQdIUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH/2Q==',0,0);

/*Table structure for table `sys_operation_log` */

CREATE TABLE `sys_operation_log` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LOG_TYPE` varchar(32) DEFAULT NULL COMMENT '日志类型(字典)',
  `LOG_NAME` varchar(255) DEFAULT NULL COMMENT '日志名称',
  `USER_ID` bigint(65) DEFAULT NULL COMMENT '用户id',
  `CLASS_NAME` varchar(255) DEFAULT NULL COMMENT '类名称',
  `METHOD` text COMMENT '方法名称',
  `SUCCEED` varchar(32) DEFAULT NULL COMMENT '是否成功(字典)',
  `MESSAGE` text COMMENT '备注',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='操作日志';

/*Data for the table `sys_operation_log` */

/*Table structure for table `sys_resources` */

CREATE TABLE `sys_resources` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `PID` bigint(30) NOT NULL DEFAULT '0' COMMENT '父ID',
  `NAME` varchar(30) DEFAULT NULL COMMENT '名称',
  `ICON` varchar(40) DEFAULT NULL COMMENT '图标',
  `TYPE` varchar(1) DEFAULT NULL COMMENT '类型,1:url 2:method',
  `URL` varchar(200) DEFAULT NULL COMMENT '链接',
  `SORT` int(10) DEFAULT NULL COMMENT '排序',
  `NOTES` varchar(50) DEFAULT NULL COMMENT '描述',
  `LEVELS` int(1) DEFAULT '0' COMMENT '层级',
  `ISMENU` varchar(1) NOT NULL DEFAULT 'N' COMMENT '是否是菜单',
  `ENABLED` int(1) NOT NULL DEFAULT '0' COMMENT '是否被禁用 0禁用1正常',
  `ISYS` int(1) NOT NULL DEFAULT '0' COMMENT '是否是超级权限 0非1是',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='资源表';

/*Data for the table `sys_resources` */

insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (1,'2017-11-11 00:00:00',NULL,0,'后台管理',NULL,'U','#',1,'用户登陆后台跳转页',1,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (2,'2017-11-11 00:00:00',NULL,1,'系统管理',NULL,'U','#',1,'系统管理',2,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (3,'2017-11-11 00:00:00',NULL,2,'用户列表',NULL,'U','/admin/user/list',1,'用户管理列表页',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (4,'2017-11-11 00:00:00',NULL,3,'用户保存',NULL,'U','/admin/user/save',1,'用户管理保存更新',4,'N',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (5,'2017-11-11 00:00:00',NULL,2,'角色列表',NULL,'U','/admin/role/list',2,'角色管理的列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (6,'2017-11-11 00:00:00',NULL,5,'角色保存',NULL,'U','/admin/role/save',1,'角色保存与更新',4,'N',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (7,'2017-11-11 00:00:00',NULL,2,'资源列表',NULL,'U','/admin/res/list',3,'资源管理列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (8,'2017-11-11 00:00:00',NULL,7,'资源保存',NULL,'U','/admin/res/save',1,'资源管理的保存',4,'N',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (9,'2017-11-11 00:00:00',NULL,2,'部门列表',NULL,'U','/admin/dept/list',4,'部门管理列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (10,'2017-11-11 00:00:00',NULL,9,'部门保存',NULL,'U','/admin/dept/save',1,'部门保存与更新',4,'N',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (11,'2017-11-11 00:00:00',NULL,2,'字典列表',NULL,'U','/admin/dict/list',5,'字典管理列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (12,'2017-11-11 00:00:00',NULL,11,'字典保存',NULL,'U','/admin/dict/save',1,'字典保存与更新',4,'N',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (13,'2017-11-11 00:00:00',NULL,2,'日志列表',NULL,'U','/admin/log/list',6,'日志列表列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (14,'2017-11-11 00:00:00',NULL,1,'首页管理',NULL,'U','#',2,'首页管理',2,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (15,'2017-11-11 00:00:00',NULL,14,'顶部列表',NULL,'U','/admin/lms/top/list',1,'模型列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (16,'2017-11-11 00:00:00',NULL,1,'题库管理',NULL,'U','#',4,'题库管理',2,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (17,'2017-11-11 00:00:00',NULL,16,'题库列表',NULL,'U','/admin/lms/question/list',1,'题库列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (18,'2017-11-11 00:00:00',NULL,16,'答案列表',NULL,'U','/admin/lms/question/answer/list',2,'题库答案列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (19,'2017-11-11 00:00:00',NULL,16,'错题科目',NULL,'U','/admin/lms/question/wrong/list',3,'题库错题列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (20,'2017-11-11 00:00:00',NULL,16,'题库材料',NULL,'U','/admin/lms/question/material/list',4,'题库材料列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (21,'2017-11-11 00:00:00',NULL,1,'答题室管理',NULL,'U','#',5,'答题室管理',2,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (22,'2017-11-11 00:00:00',NULL,21,'答题室列表',NULL,'U','/admin/lms/exam/room/list',1,'答题室列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (23,'2017-11-11 00:00:00',NULL,21,'统计列表',NULL,'U','/admin/lms/exam/log/list',2,'答题统计列表',3,'Y',1,0,NULL,NULL);
insert  into `sys_resources`(`ID`,`CTIME`,`CUSER`,`PID`,`NAME`,`ICON`,`TYPE`,`URL`,`SORT`,`NOTES`,`LEVELS`,`ISMENU`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (24,'2017-11-11 00:00:00',NULL,21,'分类列表',NULL,'U','/admin/lms/exam/subject/list',3,'学科分类列表',3,'Y',1,0,NULL,NULL);

/*Table structure for table `sys_role` */

CREATE TABLE `sys_role` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `ROLE_NAME` varchar(50) DEFAULT NULL COMMENT '角色名字',
  `NOTES` varchar(100) DEFAULT NULL COMMENT '角色说明',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被禁用 0禁用1正常',
  `ISYS` int(1) NOT NULL DEFAULT '0' COMMENT '是否是超级权限 0非1是',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='角色表';

/*Data for the table `sys_role` */

insert  into `sys_role`(`ID`,`CTIME`,`CUSER`,`ROLE_NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (1,'2017-11-11 00:00:00',NULL,'ROLE_ROOT','拥有管理后台最高权限',1,1,NULL,NULL);
insert  into `sys_role`(`ID`,`CTIME`,`CUSER`,`ROLE_NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (2,'2017-11-11 00:00:00',NULL,'ROLE_SYSTEM','拥有管理后台系统权限',1,1,NULL,NULL);
insert  into `sys_role`(`ID`,`CTIME`,`CUSER`,`ROLE_NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (3,'2017-11-11 00:00:00',NULL,'ROLE_ADMIN','拥有管理后台操作权限',1,1,NULL,NULL);
insert  into `sys_role`(`ID`,`CTIME`,`CUSER`,`ROLE_NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (4,'2017-11-11 00:00:00',NULL,'ROLE_USER_TEST','用来测试的用户角色',1,0,NULL,NULL);
insert  into `sys_role`(`ID`,`CTIME`,`CUSER`,`ROLE_NAME`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (5,'2017-11-11 00:00:00',NULL,'ROLE_USER','普通用户角色',1,0,NULL,NULL);

/*Table structure for table `sys_role_auth` */

CREATE TABLE `sys_role_auth` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` bigint(30) DEFAULT NULL COMMENT '角色id',
  `AUTH_ID` bigint(30) DEFAULT NULL COMMENT '权限id',
  PRIMARY KEY (`ID`),
  KEY `role_id` (`ROLE_ID`),
  KEY `auth_id` (`AUTH_ID`),
  CONSTRAINT `sys_role_auth_ibfk_1` FOREIGN KEY (`ROLE_ID`) REFERENCES `sys_role` (`ID`),
  CONSTRAINT `sys_role_auth_ibfk_2` FOREIGN KEY (`AUTH_ID`) REFERENCES `sys_authorities` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='角色权限关联表';

/*Data for the table `sys_role_auth` */

insert  into `sys_role_auth`(`ID`,`ROLE_ID`,`AUTH_ID`) values (1,1,1);
insert  into `sys_role_auth`(`ID`,`ROLE_ID`,`AUTH_ID`) values (2,4,4);

/*Table structure for table `sys_user` */

CREATE TABLE `sys_user` (
  `ID` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CUSER` bigint(30) DEFAULT NULL COMMENT '创建人',
  `RID` bigint(10) DEFAULT NULL COMMENT '角色ID',
  `NAME` varchar(30) DEFAULT NULL COMMENT '用户姓名',
  `USERNAME` varchar(30) DEFAULT NULL COMMENT '登陆用户名(登陆号)',
  `PASSWORD` varchar(50) DEFAULT NULL COMMENT '用户密码',
  `NOTES` varchar(50) DEFAULT NULL COMMENT '描述',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0' COMMENT '禁用状态: 0-禁用,1-正常',
  `ISYS` int(1) NOT NULL DEFAULT '0' COMMENT '是否是超级用户 0非1是',
  `ETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `EUSER` bigint(30) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户表';

/*Data for the table `sys_user` */

insert  into `sys_user`(`ID`,`CTIME`,`CUSER`,`RID`,`NAME`,`USERNAME`,`PASSWORD`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (1,'2017-11-11 00:00:00',NULL,1,'管理员','admin','21232f297a57a5a743894a0e4a801fc3','系统超级管理员',1,1,NULL,NULL);
insert  into `sys_user`(`ID`,`CTIME`,`CUSER`,`RID`,`NAME`,`USERNAME`,`PASSWORD`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (2,'2017-11-11 00:00:00',NULL,4,'测试用户','user','21232f297a57a5a743894a0e4a801fc3','测试用户',1,0,NULL,NULL);
insert  into `sys_user`(`ID`,`CTIME`,`CUSER`,`RID`,`NAME`,`USERNAME`,`PASSWORD`,`NOTES`,`ENABLED`,`ISYS`,`ETIME`,`EUSER`) values (3,'2017-11-11 00:00:00',NULL,NULL,'3','3','21232f297a57a5a743894a0e4a801fc3','1123333',1,0,NULL,NULL);

/* Trigger structure for table `lms_exam_room` */

DELIMITER $$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `before_insert_exam_room` BEFORE INSERT ON `lms_exam_room` FOR EACH ROW BEGIN
	SET NEW.`UUID` = UUID();
    END */$$


DELIMITER ;

/* Trigger structure for table `lms_question_material` */

DELIMITER $$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `before_insert_question_material` BEFORE INSERT ON `lms_question_material` FOR EACH ROW BEGIN
	SET NEW.`UUID` = UUID();
    END */$$


DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
